services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      # You can point to dev/test/prod depending on what you want to run
      DJANGO_SETTINGS_MODULE: core.settings.dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dev_db
      POSTGRES_HOST: db_dev
      POSTGRES_PORT: 5433
      RABBITMQ_HOST: rabbitmq
    env_file:
      - .env
    depends_on:
      - db_dev
      - db_test
      - db_prod
      - rabbitmq

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: celery_worker
    command: celery -A core worker --loglevel=info
    volumes:
      - .:/app
    environment:
      DJANGO_SETTINGS_MODULE: core.settings.dev
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dev_db
      POSTGRES_HOST: db_dev
      POSTGRES_PORT: 5433
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - db_dev
      - rabbitmq

  db_dev:
    image: postgres:16-alpine
    container_name: postgres_dev
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: dev_db
    volumes:
      - pgdata_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  db_test:
    image: postgres:16-alpine
    container_name: postgres_test
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: test_db
    volumes:
      - pgdata_test:/var/lib/postgresql/data
    ports:
      - "5434:5432"

  db_prod:
    image: postgres:16-alpine
    container_name: postgres_prod
    environment:
      POSTGRES_USER: produser
      POSTGRES_PASSWORD: prodpass
      POSTGRES_DB: prod_db
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  rabbitmq:
    image: rabbitmq:3.13.7-management
    container_name: rabbitmq_broker
    ports:
      - "5672:5672"   # RabbitMQ broker
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  pgdata_dev:
  pgdata_test:
  pgdata_prod:
  redis_data:
